import { dbService, User, MaterialChunk, ClassroomParticipantIdentity } from '../services/db.service';
import { PdfService } from '../services/pdf.service';
import { RAGEngine } from '../services/rag/ragEngine';

async function runProductionE2EVerification() {
  console.log('====================================================');
  console.log('🚀 Starting ClassPulse Production E2E Verification');
  console.log('====================================================\n');

  let passed = 0;
  let failed = 0;

  function assert(condition: boolean, testName: string, detail?: string) {
    if (condition) {
      console.log(`✅ [PASS] ${testName}`);
      passed++;
    } else {
      console.error(`❌ [FAIL] ${testName} ${detail ? `(${detail})` : ''}`);
      failed++;
    }
  }

  // TEST 1: Passwordless Email + OTP User Resolution Flow
  console.log('--- TEST 1: Email + OTP User Resolution Flow ---');
  const testEmail = 'prof.maxwell@physics.org';
  const testName = 'James Clerk Maxwell';

  let user = dbService.getUserByEmail(testEmail);
  if (!user) {
    user = dbService.createUser({
      id: `usr_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      email: testEmail,
      name: testName,
      avatarUrl: `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(testName)}`,
      role: 'TEACHER',
      createdAt: new Date().toISOString(),
      lastLoginAt: new Date().toISOString(),
    });
  }

  assert(user.role === 'TEACHER' && user.name === testName, 'Test 1A: User profile created with authoritative TEACHER role');

  const authSession = dbService.createAuthSession(user.id);
  assert(authSession.token.startsWith('cps_'), 'Test 1B: Secure session token issued');

  const resolved = dbService.getAuthSession(authSession.token);
  assert(resolved?.user.id === user.id, 'Test 1C: Auth session resolves correct user identity');

  // TEST 2: Authoritative Classroom Roster Mapping
  console.log('\n--- TEST 2: Authoritative Classroom Roster Mapping ---');
  const testClassId = `CLS_E2E_${Date.now()}`;
  const teacherAgoraUid = 10001;
  const studentAgoraUid = 10002;

  const teacherIdentity: ClassroomParticipantIdentity = {
    agoraUid: teacherAgoraUid,
    userId: user.id,
    displayName: user.name,
    email: user.email,
    role: 'TEACHER',
    avatarUrl: user.avatarUrl,
    joinedAt: new Date().toISOString(),
  };
  dbService.registerActiveParticipant(testClassId, teacherIdentity);

  const studentUser: User = {
    id: `usr_student_${Date.now()}`,
    email: 'student.kevin@school.edu',
    name: 'Kevin Student',
    avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Kevin',
    role: 'STUDENT',
    createdAt: new Date().toISOString(),
    lastLoginAt: new Date().toISOString(),
  };
  dbService.createUser(studentUser);

  const studentIdentity: ClassroomParticipantIdentity = {
    agoraUid: studentAgoraUid,
    userId: studentUser.id,
    displayName: studentUser.name,
    email: studentUser.email,
    role: 'STUDENT',
    joinedAt: new Date().toISOString(),
  };
  dbService.registerActiveParticipant(testClassId, studentIdentity);

  const liveRoster = dbService.getActiveRoster(testClassId);
  assert(liveRoster[teacherAgoraUid]?.displayName === 'James Clerk Maxwell', 'Test 2A: Teacher Agora UID maps to real display name');
  assert(liveRoster[studentAgoraUid]?.displayName === 'Kevin Student', 'Test 2B: Student Agora UID maps to real display name');
  assert(liveRoster[studentAgoraUid]?.role === 'STUDENT', 'Test 2C: Authoritative student role mapped');

  // TEST 3: PDF Ingestion & Semantic Chunking
  console.log('\n--- TEST 3: PDF Ingestion & Semantic Chunking ---');
  const pdfHeader = '%PDF-1.4\n';
  const isPdf = PdfService.isValidPdfBuffer(Buffer.from(pdfHeader));
  assert(isPdf, 'Test 3A: PdfService correctly identifies %PDF- magic bytes header');

  const invalidHeader = PdfService.isValidPdfBuffer(Buffer.from('NOT_A_PDF'));
  assert(!invalidHeader, 'Test 3B: PdfService rejects non-PDF buffers');

  const sampleMaterialId = `mat_${Date.now()}`;
  const mockChunks: MaterialChunk[] = [
    {
      id: `chk_${sampleMaterialId}_0`,
      materialId: sampleMaterialId,
      classId: testClassId,
      title: 'Electromagnetism Lecture Notes',
      pageNumber: 1,
      chunkIndex: 0,
      content: 'Maxwell equations describe how electric and magnetic fields are generated by charges, currents, and changes of the fields. Gauss law states that the net electric flux through any closed Gaussian surface is equal to 1/ε₀ times the net electric charge enclosed.',
      tokenCount: 45,
    },
    {
      id: `chk_${sampleMaterialId}_1`,
      materialId: sampleMaterialId,
      classId: testClassId,
      title: 'Electromagnetism Lecture Notes',
      pageNumber: 2,
      chunkIndex: 1,
      content: 'Faraday law of induction states that the electromotive force around a closed loop is equal to the negative of the time rate of change of the magnetic flux through the loop. Ampere Maxwell law accounts for magnetic fields created by displacement currents.',
      tokenCount: 46,
    }
  ];

  dbService.addMaterialChunks(mockChunks);
  const storedChunks = dbService.getMaterialChunksForClass(testClassId);
  assert(storedChunks.length === 2, 'Test 3C: Semantic chunks stored and indexed for classroom');

  // TEST 4: Class-Scoped PDF RAG Retrieval with Page Citations
  console.log('\n--- TEST 4: Class-Scoped RAG Retrieval & Citations ---');
  const ragEngine = new RAGEngine();

  const mockSession: any = {
    id: `sess_${Date.now()}`,
    classId: testClassId,
    meetingUrl: 'classpulse://classroom',
    participantId: studentUser.id,
    participantName: studentUser.name,
    startedAt: new Date().toISOString(),
    recentQuestions: [],
    conversationHistory: [],
  };

  const ragResult = ragEngine.processQuery('What does Faraday law of induction state?', mockSession);
  assert(ragResult.isEducational, 'Test 4A: RAG engine categorizes query as educational');
  assert(ragResult.answerText.includes('Faraday law'), 'Test 4B: RAG answer contains content extracted from uploaded material');
  assert(ragResult.chapter === 'Page 2' && ragResult.answerText.includes('Page 2'), 'Test 4C: RAG response includes exact page citation (Page 2)');

  // TEST 5: Leave & Participant Cleanup
  console.log('\n--- TEST 5: Classroom Cleanup on Participant Leave ---');
  dbService.removeActiveParticipant(testClassId, studentAgoraUid);
  const updatedRoster = dbService.getActiveRoster(testClassId);
  assert(updatedRoster[studentAgoraUid] === undefined, 'Test 5A: Student removed from active roster on leave');
  assert(updatedRoster[teacherAgoraUid] !== undefined, 'Test 5B: Remaining participants preserved in roster');

  console.log('\n====================================================');
  console.log(`🎉 Production E2E Summary: ${passed} Passed, ${failed} Failed`);
  console.log('====================================================\n');

  if (failed > 0) {
    process.exit(1);
  }
}

runProductionE2EVerification().catch((err) => {
  console.error('Fatal test error:', err);
  process.exit(1);
});
